### ISSUE TITLE
Pulse Circuit throws error

### ISSUE THREAD

**Issue by glitchcowboy** [Dan-in-CA/ospi_plugins#5]
After I install the Pulse Circuit plugin, I choose Pulse Circuit from the plugins menu and the console throws this:
Traceback (most recent call last):
  File "/home/pi/OSPi/web/application.py", line 239, in process
    return self.handle()
  File "/home/pi/OSPi/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/pi/OSPi/web/application.py", line 423, in _delegate
    return handle_class(cls)
  File "/home/pi/OSPi/web/application.py", line 399, in handle_class
    return tocall(*args)
  File "/home/pi/OSPi/plugins/pulse_cct.py", line 44, in GET
    return render.pulse(pform, "Open Sprinkler")#monthly(levels)
  File "/home/pi/OSPi/web/template.py", line 881, in __call__
    return BaseTemplate.__call__(self, *a, **kw)
  File "/home/pi/OSPi/web/template.py", line 808, in __call__
    return self.t(*a, **kw)
TypeError: __template__() takes no arguments (2 given)

192.168.0.7:50550 - - [10/Apr/2015 22:08:36] "HTTP/1.1 GET /pls" - 500 Internal Server Error
 
While the browser (Safari Version 8.0.4 (10600.4.10.7)) says "internal server error"

**Comment by Dan-in-CA** [comment]
I didn't see the problem you describe but I have updated the plugin so that it now shows all stations depending on the number of expansion boards. It also allows for enabling and disabling stations. I think it is now a fairly useful utility for testing and setting up a system. Thanks for the input.
